// Coal by Arthur Shlain from the Noun Project
// Flame by Daniel DeLorenzo from the Noun Project
// Radiation symbol by icon 54 from the Noun Project
// Oil by Orin zuu from the Noun Project
// Flame by Neha Shinde from the Noun Project
import {keyBy} from 'lodash'

export const CITIES = [
  [50, 25, 'yellow', 'Calgary'],
  [120, 25, 'yellow', 'Edmonton'],
  [10, 75, 'yellow', 'Vancouver'],
  [215, 45, 'yellow', 'Winnipeg'],
  [130, 85, 'yellow', 'Regina'],
  [10, 125, 'yellow', 'Seattle'],
  [290, 45, 'yellow', 'Minneapolis'],
  [10, 175, 'cyan', 'Portland'],
  [10, 225, 'cyan', 'San Francisco'],
  [30, 275, 'cyan', 'Los Angeles'],
  [40, 325, 'cyan', 'San Diego'],
  [85, 175, 'cyan', 'Salt Lake City'],
  [160, 200, 'cyan', 'Denver'],
  [100, 235, 'cyan', 'Las Vegas'],
  [365, 25, 'brown', 'Milwaukee'],
  [365, 75, 'brown', 'Chicago'],
  [365, 125, 'brown', 'Indianapolis'],
  [385, 220, 'brown', 'Memphis'],
  [275, 220, 'brown', 'Oklahoma City'],
  [305, 160, 'brown', 'St Louis'],
  [230, 160, 'brown', 'Kansas City'],

  [450, 25, 'red', 'Detroit'],
  [525, 25, 'red', 'Toronto'],
  [450, 100, 'red', 'Columbus'],
  [450, 170, 'red', 'Nashville'],
  [525, 100, 'red', 'Pittsburgh'],
  [545, 150, 'red', 'Washington'],
  [545, 200, 'red', 'Charlotte'],
  [630, 25, 'green', 'Ottawa'],
  [630, 100, 'green', 'New York'],
  [700, 180, 'green', 'New York 2'],
  [630, 150, 'green', 'Philadelphia'],
  [700, 25, 'green', 'Quebec'],
  [700, 75, 'green', 'Montreal'],
  [700, 125, 'green', 'Boston'],

  [200, 250, 'purple', 'Albuquerque'],
  [200, 300, 'purple', 'Juarez'],
  [215, 350, 'purple', 'Chihuahua'],
  [250, 400, 'purple', 'Guadalajara'],
  [300, 360, 'purple', 'Monterrey'],
  [350, 400, 'purple', 'Mexico City'],
  [420, 400, 'purple', 'Mexico City 2'],
  [370, 325, 'orange', 'San Antonio'],
  [340, 265, 'orange', 'Fort Worth'],
  [450, 325, 'orange', 'Houston'],
  [520, 325, 'orange', 'New Orleans'],
  [540, 275, 'orange', 'Atlanta'],
  [600, 325, 'orange', 'Jacksonville'],
  [600, 375, 'orange', 'Miami'],
]

export const CITIES_BY_NAME = keyBy(CITIES, c => c[3])

export const EDGES = [
  ['Vancouver', 'Seattle', 4],
  ['Vancouver', 'Calgary', 16],
  ['Vancouver', 'Regina', 28],
  ['Edmonton', 'Regina', 15],
  ['Calgary', 'Edmonton', 5],
  ['Calgary', 'Regina', 14],
  ['Regina', 'Winnipeg', 11],
  ['Winnipeg', 'Minneapolis', 13],
  ['Seattle', 'Portland', 5],
  ['Regina', 'Salt Lake City', 29],
  ['Regina', 'Denver', 24],
  ['Winnipeg', 'Denver', 26],
  ['Minneapolis', 'Denver', 23],
  ['Minneapolis', 'Kansas City', 14],
  ['Minneapolis', 'Milwaukee', 10],

  ['Portland', 'San Francisco', 20],
  ['Portland', 'Salt Lake City', 22],
  ['San Francisco', 'Salt Lake City', 22],
  ['San Francisco', 'Las Vegas', 16],
  ['San Francisco', 'Los Angeles', 12],
  ['Los Angeles', 'Las Vegas', 8],
  ['Los Angeles', 'San Diego', 3],
  ['Las Vegas', 'Denver', 25],
  ['Las Vegas', 'Salt Lake City', 14],
  ['Salt Lake City', 'Denver', 14],
  ['Los Angeles', 'Albuquerque', 25],
  ['Las Vegas', 'Albuquerque', 18],
  ['Denver', 'Albuquerque', 12],
  ['San Diego', 'Juarez', 22],
  ['Denver', 'Kansas City', 19],
  ['Denver', 'Oklahoma City', 17],

  ['Albuquerque', 'Juarez', 9],
  ['Juarez', 'Chihuahua', 8],
  ['Chihuahua', 'Guadalajara', 23],
  ['Chihuahua', 'Monterrey', 14],
  ['Guadalajara', 'Monterrey', 16],
  ['Mexico City', 'Monterrey', 17],
  ['Mexico City', 'Mexico City 2', 0],
  ['Mexico City', 'Guadalajara', 10],
  ['Albuquerque', 'Oklahoma City', 18],
  ['Juarez', 'Fort Worth', 19],
  ['Juarez', 'San Antonio', 18],
  ['Chihuahua', 'San Antonio', 16],
  ['Monterrey', 'San Antonio', 10],

  ['Oklahoma City', 'Kansas City', 10],
  ['Oklahoma City', 'Memphis', 15],
  ['Kansas City', 'St Louis', 8],
  ['Kansas City', 'Memphis', 14],
  ['Kansas City', 'Chicago', 16],
  ['St Louis', 'Memphis', 9],
  ['St Louis', 'Chicago', 9],
  ['St Louis', 'Indianapolis', 8],
  ['Chicago', 'Milwaukee', 3],
  ['Chicago', 'Indianapolis', 6],
  ['Oklahoma City', 'Fort Worth', 7],
  ['Memphis', 'Fort Worth', 15],
  ['Memphis', 'New Orleans', 14],
  ['Memphis', 'Atlanta', 12],
  ['Memphis', 'Nashville', 7],
  ['St Louis', 'Nashville', 9],
  ['Indianapolis', 'Nashville', 9],
  ['Indianapolis', 'Columbus', 7],
  ['Chicago', 'Columbus', 10],
  ['Chicago', 'Detroit', 10],

  ['Fort Worth', 'San Antonio', 9],
  ['Fort Worth', 'Houston', 8],
  ['Fort Worth', 'New Orleans', 16],
  ['Houston', 'San Antonio', 6],
  ['Houston', 'New Orleans', 12],
  ['New Orleans', 'Atlanta', 16],
  ['New Orleans', 'Jacksonville', 20],
  ['Atlanta', 'Jacksonville', 10],
  ['Miami', 'Jacksonville', 12],
  ['Atlanta', 'Nashville', 8],
  ['Atlanta', 'Charlotte', 8],
  ['Jacksonville', 'Charlotte', 12],

  ['Nashville', 'Charlotte', 12],
  ['Nashville', 'Washington', 22],
  ['Nashville', 'Columbus', 15],
  ['Columbus', 'Washington', 12],
  ['Columbus', 'Detroit', 7],
  ['Columbus', 'Pittsburgh', 6],
  ['Charlotte', 'Washington', 12],
  ['Washington', 'Pittsburgh', 7],
  ['Detroit', 'Toronto', 8],
  ['Pittsburgh', 'Toronto', 11],
  ['Toronto', 'Ottawa', 8],
  ['Toronto', 'New York', 8],
  ['Pittsburgh', 'New York', 11],
  ['Pittsburgh', 'Philadelphia', 9],
  ['Washington', 'Philadelphia', 5],

  ['Ottawa', 'New York', 13],
  ['Ottawa', 'Montreal', 3],
  ['Quebec', 'Montreal', 5],
  ['Boston', 'Montreal', 9],
  ['Boston', 'New York', 7],
  ['New York', 'Montreal', 12],
  ['New York', 'New York 2', 0],
  ['New York', 'Philadelphia', 3],
]
