import {
  DecreaseAnyProduction,
  DecreaseAnyInventory,
  ChangeInventory,
  ChangeProduction,
  ChangeAnyCardResource,
  IncreaseTR,
  Draw,
  Choice,
  IncreaseTemperature,
  PlaceOceans,
  PlaceNoctis,
  PlaceResearchOutpost,
  ChangeCardResource,
  Discount,
  PlaceCity,
  AfterCard,
  RaiseOxygen,
  Branch,
  HasTags,
  GetTags,
  PlaceGreeneryOnOcean,
  LandClaim,
  RoboticWorkforce,
  GetCities,
  GetOpponentTags,
  GetAllTags,
  ArtificialLake,
  UrbanizedArea,
  GetCitiesOnMars,
  Mohole,
  GetX,
  Neg,
  PlaceGreenery,
  MaxOxygen,
  MinOceans,
  MinOxygen,
  MaxHeat,
  MinHeat,
  HasCitiesOnMars,
  MaxOceans,
} from './utils'
import {ResourceType, CardResource, Tag} from './types'

export const CARDS = [
  {
    name: 'Colonizer Training Camp',
    cost: 8,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Jovian'],
    globalRequirements: {Oxygen: [null, 5]},
    TR: 0,
    vp: 2,
    placeTiles: false,
    effectText: 'Oxygen must be 5% or less.',
    requires: [MaxOxygen(5)],
  },
  {
    name: 'Asteroid Mining Consortium',
    cost: 13,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Jovian'],
    inventory: {Titanium: 'Ref'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText:
      'Requires that you have titanium production. Decrease any titanium production 1 step and increase your own 1 step.',
    effects: [DecreaseAnyProduction(-1, 'titanium'), ChangeProduction(1, 'titanium')],
  },
  {
    name: 'Deep Well Heating',
    cost: 13,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Energy'],
    production: {Energy: '1'},
    terraforming: {Temperature: 1, Oxygen: 0, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your energy production 1 step. Increase temperature 1 step.',
    effects: [ChangeProduction(1, ResourceType.Energy), IncreaseTemperature(1)],
  },
  {
    name: 'Cloud Seeding',
    cost: 11,
    type: 'Automated',
    deck: 'Basic',
    globalRequirements: {Oceans: [3, null]},
    production: {Money: '-1', Plant: '2', Heat: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Requires 3 ocean tiles. Decrease your MC production 1 step and any heat production 1 step.  Increase your plant production 2 steps.',
    effects: [
      ChangeProduction(-1, ResourceType.Money),
      DecreaseAnyProduction(1, ResourceType.Heat),
      ChangeProduction(2, ResourceType.Plant),
    ],
    requires: [MinOceans(3)],
  },
  {
    name: 'Search For Life',
    cost: 3,
    type: 'Active',
    deck: 'Basic',
    tags: ['Science'],
    globalRequirements: {Oxygen: [null, 6]},
    inventory: {Money: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText:
      'Action: Spend 1 MC to reveal and discard the top card of the draw deck. If that card has a microbe tag, add a science resource here.',
    effectText: 'Oxygen must be 6% or less. 3 VPs if you have one or more science resource here.',
    resourceHeld: CardResource.Science,
    requires: [MaxOxygen(6)],
  },
  {
    name: "Inventors' Guild",
    cost: 9,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Science'],
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Action: Look at the top card and either buy it or discard it',
  },
  {
    name: 'Martian Rail',
    cost: 13,
    type: 'Active',
    deck: 'Basic',
    tags: ['Building'],
    inventory: {Money: 'Ref', Energy: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Action: Spend 1 energy to gain 1 MC for each city tile ON MARS.',
  },
  {
    name: 'Capital',
    cost: 26,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'City'],
    globalRequirements: {Oceans: [4, null]},
    production: {Money: '5', Energy: '-2'},
    TR: 0,
    placeTiles: true,
    effectText:
      'Requires 4 ocean tiles. Place [the capital city] tile. Decrease your energy production 2 steps and increase your MC production 5 steps. 1 ADDITIONAL VP FOR EACH OCEAN TILE ADJACENT TO THIS CITY TILE.',
    requires: [MinOceans(4)],
  },
  {
    name: 'Asteroid',
    cost: 14,
    type: 'Event',
    deck: 'Basic',
    tags: ['Space', 'Event'],
    inventory: {Titanium: '2', Plant: 'Ref'},
    terraforming: {Temperature: 1, Oxygen: 0, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Raise temperature 1 step and gain 2 titanium. Remove up to 3 plants from any player.',
  },
  {
    name: 'Comet',
    cost: 21,
    type: 'Event',
    deck: 'Basic',
    tags: ['Space', 'Event'],
    inventory: {Plant: 'Ref'},
    terraforming: {Temperature: 1, Oxygen: 0, Ocean: 1},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText:
      'Raise temperature 1 step and place an ocean tile. Remove up to 3 plants from any player.',
    effects: [IncreaseTemperature(1), PlaceOceans(1), DecreaseAnyInventory(3, ResourceType.Plant)],
  },
  {
    name: 'Big Asteroid',
    cost: 27,
    type: 'Event',
    deck: 'Basic',
    tags: ['Space', 'Event'],
    inventory: {Titanium: '4', Plant: 'Ref'},
    terraforming: {Temperature: 2, Oxygen: 0, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Raise temperature 2 steps and gain 4 titanium. Remove up to 4 plants from any player.',
    effects: [
      IncreaseTemperature(2),
      ChangeInventory(4, ResourceType.Titanium),
      DecreaseAnyInventory(4, ResourceType.Plant),
    ],
  },
  {
    name: 'Water Import From Europa',
    cost: 25,
    type: 'Active',
    deck: 'Basic',
    tags: ['Space', 'Jovian'],
    inventory: {Money: 'Ref', Titanium: 'Ref'},
    terraforming: {Temperature: 0, Oxygen: 0, Ocean: null},
    TR: 0,
    placeTiles: false,
    actionText:
      'Action: Pay 12 MC to place an ocean tile. TITANIUM MAY BE USED as if playing a space card.',
    effectText: '1 VP for each Jovian tag you have.',
  },
  {
    name: 'Space Elevator',
    cost: 27,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Building', 'Space'],
    production: {Titanium: '1'},
    inventory: {Money: 'Ref', Steel: 'Ref'},
    TR: 0,
    vp: 2,
    actionText: 'Action: Spend 1 steel to gain 5 MC',
    effectText: 'Increase your titanium production 1 step.',
    actions: [[ChangeInventory(-1, ResourceType.Titanium), ChangeInventory(5, ResourceType.Money)]],
    effect: [ChangeProduction(1, ResourceType.Titanium)],
  },
  {
    name: 'Development Center',
    cost: 11,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Science', 'Building'],
    inventory: {Energy: 'Ref'},
    TR: 0,
    vp: 0,
    actionText: 'Action: Spend 1 energy to draw a card.',
    actions: [[ChangeInventory(-1, ResourceType.Energy), Draw(1)]],
  },
  {
    name: 'Equatorial Magnetizer',
    cost: 11,
    type: 'Active',
    deck: 'Basic',
    tags: ['Building'],
    production: {Energy: 'Ref'},
    vp: 0,
    placeTiles: false,
    actionText:
      'Action: Decrease your energy production 1 step to increase your terraforming rating 1 step.',
    actions: [[ChangeProduction(-1, ResourceType.Energy), IncreaseTR(1)]],
  },
  {
    name: 'Domed Crater',
    cost: 24,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'City'],
    globalRequirements: {Oxygen: [null, 7]},
    production: {Money: '3', Energy: '-1'},
    inventory: {Plant: '3'},
    TR: 0,
    vp: 1,
    placeTiles: true,
    effectText:
      'Oxygen must be 7% or less. Gain 3 plants and place a city tile. Decrease your energy production 1 step and increase MC production 3 steps.',
    requires: [MaxOxygen(7)],
  },
  {
    name: 'Noctis City',
    cost: 18,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'City'],
    production: {Money: '3', Energy: '-1'},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText:
      'Decrease your energy production 1 step and increase your MC production 3 steps. Place a tile ON THE RESERVED AREA, disregarding normal placement restrictions.',
    effects: [
      ChangeProduction(-1, ResourceType.Energy),
      ChangeProduction(3, ResourceType.Money),
      PlaceNoctis,
    ],
  },
  {
    name: 'Methane From Titan',
    cost: 28,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Space', 'Jovian'],
    globalRequirements: {Oxygen: [2, null]},
    production: {Plant: '2', Heat: '2'},
    TR: 0,
    vp: 2,
    placeTiles: false,
    effectText:
      'Requires 2% oxygen. Increase your heat production 2 steps and your plant production 2 steps.',
    effects: [ChangeProduction(2, ResourceType.Heat), ChangeProduction(2, ResourceType.Plant)],
    requires: [MinOxygen(2)],
  },
  {
    name: 'Imported Hydrogen',
    cost: 16,
    type: 'Event',
    deck: 'Basic',
    tags: ['Space', 'Earth', 'Event'],
    inventory: {Plant: 'Ref'},
    terraforming: {Temperature: 0, Oxygen: 0, Ocean: 1},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText:
      'Gain 3 plants, or add 3 microbes or 2 animals to ANOTHER card. Place an ocean tile.',
    effects: [
      Choice(
        ChangeInventory(3, ResourceType.Plant),
        ChangeAnyCardResource(3, CardResource.Microbes),
        ChangeAnyCardResource(2, 'Animals')
      ),
      PlaceOceans(1),
    ],
  },
  {
    name: 'Research Outpost',
    cost: 18,
    type: 'Active',
    deck: 'Basic',
    tags: ['Science', 'Building', 'City'],
    TR: 0,
    vp: 0,
    placeTiles: true,
    actionText: 'Effect: When you play a card, you pay 1 MC less for it.',
    effectText: 'Place a city tile NEXT TO NO OTHER TILE.',
    effects: [PlaceResearchOutpost],
  },
  {
    name: 'Phobos Space Haven',
    cost: 25,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Space', 'City'],
    production: {Titanium: '1'},
    TR: 0,
    vp: 3,
    placeTiles: true,
    effectText:
      'Increase your titanium production 1 step and place a city tile ON THE RESERVED AREA.',
  },
  {
    name: 'Black Polar Dust',
    cost: 15,
    type: 'Automated',
    deck: 'Basic',
    production: {Money: '-2', Heat: '3'},
    terraforming: {Temperature: 0, Oxygen: 0, Ocean: 1},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText:
      'Place an ocean tile. Decrease your MC production 2 steps and increase your heat production 3 steps.',
    effects: [
      PlaceOceans(1),
      ChangeProduction(-2, ResourceType.Money),
      ChangeProduction(3, ResourceType.Heat),
    ],
  },
  {
    name: 'Arctic Algae',
    cost: 12,
    type: 'Active',
    deck: 'Basic',
    tags: ['Plant'],
    globalRequirements: {Temperature: [null, -12]},
    inventory: {Plant: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Effect: When anyone places an ocean tile, gain 2 plants.',
    effectText: 'It must be -12\u00b0C or colder to play. Gain 1 plant.',
    effect: [ChangeInventory(1, ResourceType.Plant)],
    requires: [MaxHeat[-12]],
  },
  {
    name: 'Predators',
    cost: 14,
    type: 'Active',
    deck: 'Basic',
    tags: ['Animal'],
    globalRequirements: {Oxygen: [11, null]},
    TR: 0,
    placeTiles: false,
    actionText: 'Action: Remove 1 animal from any card and add it to this card.',
    effectText: 'Requires 11% oxygen. 1 VP per animal on this card.',
    action: [
      [
        ChangeAnyCardResource(-1, CardResource.Animals),
        ChangeCardResource(1, CardResource.Animals),
      ],
    ],
    resourceHeld: CardResource.Animals,
    requires: [MinOxygen(11)],
  },
  {
    name: 'Space Station',
    cost: 10,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Space'],
    requirements: {Microbe: ' '},
    TR: 0,
    vp: 1,
    placeTiles: false,
    actionText: 'Effect: When you play a space card, you pay 2 MC less for it.',
    triggers: [Discount(2, [Tag.Space])],
  },
  {
    name: 'Eos Chasma National Park',
    cost: 16,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Plant'],
    globalRequirements: {Temperature: [-12, null]},
    production: {Money: '2'},
    inventory: {Plant: '3'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText:
      'Requires -12C  or warmer. Add 1 animal TO ANY ANIMAL CARD. Gain 3 plants. Increase your MC production 2 steps.',
    effects: [
      ChangeAnyCardResource(1, CardResource.Animals),
      ChangeInventory(3, ResourceType.Plant),
      ChangeProduction(2, ResourceType.Money),
    ],
    requires: [MinHeat(-12)],
  },
  {
    name: 'Interstellar Colony Ship',
    cost: 24,
    type: 'Event',
    deck: 'Corporate',
    tags: ['Space', 'Earth', 'Event'],
    requirements: {Science: '5'},
    TR: 0,
    vp: 4,
    placeTiles: false,
    effectText: 'Requires 5 science tags.',
    requires: [HasTags(5, Tag.Science)],
  },
  {
    name: 'Security Fleet',
    cost: 12,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Space'],
    inventory: {Titanium: 'Ref'},
    TR: 0,
    placeTiles: false,
    actionText: 'Action: Spend 1 titanium to add 1 fighter resource to this card.',
    effectText: '1 VP for each fighter resource on this card.',
    actions: [
      [ChangeInventory(-1, ResourceType.Titanium), ChangeCardResource(1, CardResource.Fighters)],
    ],
    resourceHeld: CardResource.Fighters,
  },
  {
    name: 'Cupola City',
    cost: 16,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'City'],
    globalRequirements: {Oxygen: [null, 9]},
    production: {Money: '3', Energy: '-1'},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText:
      'Oxygen must be 9% or less. Place a city tile. Decrease your energy production 1 step and increase your MC production 3 steps.',
    effects: [
      PlaceCity,
      ChangeProduction(-1, ResourceType.Energy),
      ChangeProduction(3, ResourceType.Money),
    ],
    requires: [MaxOxygen(9)],
  },
  {
    name: 'Lunar Beam',
    cost: 13,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Earth', 'Energy'],
    production: {Money: '-2', Energy: '2', Heat: '2'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Decrease your MC production 2 steps and increase your heat production and energy production 2 steps each.',
    effects: [
      ChangeProduction(-2, ResourceType.Money),
      ChangeProduction(2, ResourceType.Heat),
      ChangeProduction(2, ResourceType.Energy),
    ],
  },
  {
    name: 'Optimal Aerobraking',
    cost: 7,
    type: 'Active',
    deck: 'Basic',
    tags: ['Space'],
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Effect: When you place a space event, you gain 3 MC and 3 heat.',
    triggers: [
      AfterCard(
        [Tag.Space],
        [ChangeInventory(3, ResourceType.Money), ChangeInventory(3, ResourceType.Heat)]
      ),
    ],
  },
  {
    name: 'Underground City',
    cost: 18,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'City'],
    production: {Steel: '2', Energy: '-2'},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText:
      'Place a city tile. Decrease your energy production 2 steps and increase your steel production 2 steps.',
    effects: [
      PlaceCity,
      ChangeProduction(-2, ResourceType.Energy),
      ChangeProduction(2, ResourceType.Steel),
    ],
  },
  {
    name: 'Regolith Eaters',
    cost: 13,
    type: 'Active',
    deck: 'Basic',
    tags: ['Science', 'Microbe'],
    terraforming: {Temperature: 0, Oxygen: null, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText:
      'Action: Add 1 microbe to this card, or remove 2 microbe from this card to raise oxygen level 1 step.',
    actions: [
      [ChangeCardResource(1, CardResource.Microbes)],
      [ChangeCardResource(-2, CardResource.Microbes), RaiseOxygen(1)],
    ],
    resourceHeld: CardResource.Microbes,
  },
  {
    name: 'GHG Producing Bacteria',
    cost: 8,
    type: 'Active',
    deck: 'Basic',
    tags: ['Science', 'Microbe'],
    globalRequirements: {Oxygen: [4, null]},
    terraforming: {Temperature: null, Oxygen: 0, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText:
      'Action: Add 1 microbe to this card, or remove 2 microbes to raise temperature 1 step.',
    actions: [
      [ChangeCardResource(1, CardResource.Microbes)],
      [ChangeCardResource(-2, CardResource.Microbes), IncreaseTemperature(1)],
    ],
    effectText: 'Requires 4% oxygen.',
    resourceHeld: CardResource.Microbes,
    requires: [MinOxygen(4)],
  },
  {
    name: 'Ants',
    cost: 9,
    type: 'Active',
    deck: 'Basic',
    tags: ['Microbe'],
    globalRequirements: {Oxygen: [4, null]},
    TR: 0,
    placeTiles: false,
    actionText: 'Action: Remove 1 microbe from any card to add 1 to this card.',
    effectText: 'Requires 4% oxygen. 1 VP per 2 microbes on this card.',
    resourceHeld: CardResource.Microbes,
    action: [
      [
        ChangeAnyCardResource(-1, CardResource.Microbes),
        ChangeCardResource(1, CardResource.Microbes),
      ],
    ],
    requires: [MinOxygen(4)],
  },
  {
    name: 'Release of Inert Gases',
    cost: 14,
    type: 'Event',
    deck: 'Basic',
    tags: ['Event'],
    TR: 2,
    vp: 0,
    placeTiles: false,
    effectText: 'Raise your terraform rating 2 steps.',
    effects: [IncreaseTR(2)],
  },
  {
    name: 'Nitrogen-Rich Asteroid',
    cost: 31,
    type: 'Event',
    deck: 'Basic',
    tags: ['Science', 'Event'],
    production: {Plant: 'Ref'},
    terraforming: {Temperature: 1, Oxygen: 0, Ocean: 0},
    TR: 2,
    vp: 0,
    placeTiles: false,
    effectText:
      'Raise your terraforming rating 2 steps and temperature 1 step. Increase your plant production 1 step, or 4 steps if you have 3 plant tags.',
    effects: [
      IncreaseTR(2),
      IncreaseTemperature(1),
      Branch(
        HasTags(3, Tag.Plant),
        ChangeProduction(4, ResourceType.Plant),
        ChangeProduction(1, ResourceType.Plant)
      ),
    ],
  },
  {
    name: 'Rover Construction',
    cost: 8,
    type: 'Active',
    deck: 'Basic',
    tags: ['Building'],
    inventory: {Money: 'Ref'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    actionText: 'Effect: When any city tile is placed, gain 2 MC',
  },
  {
    name: 'Deimos Down',
    cost: 31,
    type: 'Event',
    deck: 'Basic',
    tags: ['Space', 'Event'],
    inventory: {Steel: '4', Plant: 'Ref'},
    terraforming: {Temperature: 3, Oxygen: 0, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Raise temperature 3 steps and gain 4 steel. Remove up to 8 plants from any player.',
    effects: [
      IncreaseTemperature(3),
      ChangeInventory(4, ResourceType.Steel),
      DecreaseAnyInventory(8, ResourceType.Plant),
    ],
  },
  {
    name: 'Asteroid Mining',
    cost: 30,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Space', 'Jovian'],
    production: {Titanium: '2'},
    TR: 0,
    vp: 2,
    placeTiles: false,
    effectText: 'Increase your titanium production 2 steps.',
    effects: [ChangeProduction(2, ResourceType.Titanium)],
  },
  {
    name: 'Food Factory',
    cost: 12,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building'],
    production: {Money: '4', Plant: '-1'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText: 'Decrease your plant production 1 step and increase your MC production 4 steps.',
    effects: [ChangeProduction(-1, ResourceType.Plant), ChangeProduction(4, ResourceType.Money)],
  },
  {
    name: 'Archaebacteria',
    cost: 6,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Microbe'],
    globalRequirements: {Temperature: [null, -18]},
    production: {Plant: '1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'It must be -18\u00b0C or colder. Increase your plant production 1 step.',
    effects: [ChangeProduction(1, ResourceType.Plant)],
    requires: [MaxHeat(-18)],
  },
  {
    name: 'Carbonate Processing',
    cost: 6,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building'],
    production: {Energy: '-1', Heat: '3'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Decrease your energy production 1 step and increase your heat production 3 steps.',
    effects: [ChangeProduction(-1, ResourceType.Energy), ChangeProduction(3, ResourceType.Heat)],
  },
  {
    name: 'Natural Preserve',
    cost: 9,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Science', 'Building'],
    globalRequirements: {Oxygen: [null, 4]},
    production: {Money: '1'},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText:
      'Oxygen must be 4% or less. Place this tile NEXT TO NO OTHER TILE. Increase your MC production 1 step.',
    requires: [MaxOxygen(4)],
  },
  {
    name: 'Nuclear Power',
    cost: 10,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Energy'],
    production: {Money: '-2', Energy: '3'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Decrease your MC production 2 steps and increase your energy production 3 steps.',
    effects: [ChangeProduction(-2, ResourceType.Money), ChangeProduction(3, ResourceType.Energy)],
  },
  {
    name: 'Lightning Harvest',
    cost: 8,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Energy'],
    requirements: {Science: '3'},
    production: {Money: '1', Energy: '1'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText:
      'Requires 3 science tags. Increase your energy production and your MC production 1 step each.',
    effects: [ChangeProduction(1, ResourceType.Energy), ChangeProduction(1, ResourceType.Money)],
    requires: [HasTags(3, Tag.Science)],
  },
  {
    name: 'Algae',
    cost: 10,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Plant'],
    globalRequirements: {Oceans: [5, null]},
    production: {Plant: '2'},
    inventory: {Plant: '1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Requires 5 ocean tiles. Gain 1 plant and increase your plant production 2 steps.',
    effects: [ChangeInventory(1, ResourceType.Plant), ChangeProduction(2, ResourceType.Plant)],
    requires: [MinOceans[5]],
  },
  {
    name: 'Adapted Lichen',
    cost: 9,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Plant'],
    production: {Plant: '1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your plant production 1 step.',
    effects: [ChangeProduction(1, ResourceType.Plant)],
  },
  {
    name: 'Tardigrades',
    cost: 4,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Microbe'],
    TR: 0,
    placeTiles: false,
    actionText: 'Action: Add 1 microbe to this card.',
    effectText: '1 VP per 4 microbes on this card.',
    actions: [[ChangeCardResource(1, CardResource.Microbes)]],
    resourceHeld: CardResource.Microbes,
  },
  {
    name: 'Virus',
    cost: 1,
    type: 'Event',
    deck: 'Corporate',
    tags: ['Microbe', 'Event'],
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Remove up to 2 animals or 5 plants from any player.',
    effects: [
      Choice(
        ChangeAnyCardResource(2, CardResource.Animals),
        DecreaseAnyInventory(5, ResourceType.Plant)
      ),
    ],
  },
  {
    name: 'Miranda Resort',
    cost: 12,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Space', 'Jovian'],
    production: {Money: 'Ref'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText: 'Increase your MC production 1 step for each Earth tag you have.',
    effects: [ChangeProduction(GetTags(Tag.Earth), ResourceType.Money)],
  },
  {
    name: 'Fish',
    cost: 9,
    type: 'Active',
    deck: 'Basic',
    tags: ['Animal'],
    globalRequirements: {Temperature: [2, null]},
    production: {Plant: 'Ref'},
    TR: 0,
    placeTiles: false,
    actionText: 'Action: Add 1 animal to this card.',
    effectText:
      'Requires 2\u00b0C or warmer. Decrease any plant production 1 step. 1 VP for each animal on this card.',
    actions: [[ChangeCardResource(1, CardResource.Animals)]],
    effects: [DecreaseAnyProduction(1, ResourceType.Plant)],
    resourceHeld: CardResource.Animals,
    requires: [MinHeat(2)],
  },
  {
    name: 'Lake Marineris',
    cost: 18,
    type: 'Automated',
    deck: 'Basic',
    terraforming: {Temperature: 0, Oxygen: 0, Ocean: 2},
    TR: 0,
    vp: 2,
    placeTiles: true,
    effectText: 'Requires 0\u00b0C or warmer. Place 2 ocean tiles.',
    effects: [PlaceOceans(2)],
  },
  {
    name: 'Small Animals',
    cost: 6,
    type: 'Active',
    deck: 'Basic',
    tags: ['Animal'],
    globalRequirements: {Oxygen: [6, null]},
    production: {Plant: 'Ref'},
    TR: 0,
    placeTiles: false,
    actionText: 'Action: Add 1 animal to this card.',
    effectText:
      'Requires 6% oxygen. Decrease any plant production 1 step. 1 VP per 2 animals on this card.',
    actions: [[ChangeCardResource(1, CardResource.Animals)]],
    effects: [DecreaseAnyProduction(1, ResourceType.Plant)],
    resourceHeld: CardResource.Animals,
    requires: [MinOxygen(6)],
  },
  {
    name: 'Kelp Farming',
    cost: 17,
    type: 'Automated',
    deck: 'Basic',
    globalRequirements: {Oceans: [6, null]},
    production: {Money: '2', Plant: '3'},
    inventory: {Plant: '2'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText:
      'Requires 6 ocean tiles. Increase your MC production 2 steps and your plant production 3 steps. Gain 2 plants.',
    effects: [
      ChangeProduction(2, ResourceType.Money),
      ChangeProduction(3, ResourceType.Plant),
      ChangeInventory(2, ResourceType.Plant),
    ],
    requries: [MinOceans(6)],
  },
  {
    name: 'Mine',
    cost: 4,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Building'],
    production: {Steel: '1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your steel production 1 step.',
    effects: [ChangeProduction(1, ResourceType.Steel)],
  },
  {
    name: 'Vesta Shipyard',
    cost: 15,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Space', 'Jovian'],
    production: {Titanium: '1'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText: 'Increase your titanium production 1 step.',
    effects: [ChangeProduction(1, ResourceType.Titanium)],
  },
  {
    name: 'Beam From a Thorium Asteroid',
    cost: 32,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Space', 'Jovian', 'Energy'],
    requirements: {Jovian: '1'},
    production: {Energy: '3', Heat: '3'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText:
      'Requires a Jovian tag. Increase your heat production and energy production 3 steps each.',
    effects: [ChangeProduction(3, ResourceType.Heat), ChangeProduction(3, ResourceType.Energy)],
    requires: [HasTags(1, Tag.Jovian)],
  },
  {
    name: 'Mangrove',
    cost: 12,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Plant'],
    globalRequirements: {Temperature: [4, null]},
    terraforming: {Temperature: 0, Oxygen: 1, Ocean: 0},
    TR: 0,
    vp: 1,
    placeTiles: true,
    effectText:
      'Requires +4\u00b0C or warmer. Place a Greenery tile ON AN AREA RESERVED FOR OCEAN and raise oxygen 1 step. Disregard normal placement restrictions for this.',
    effects: [PlaceGreeneryOnOcean],
    requires: [MinHeat(4)],
  },
  {
    name: 'Trees',
    cost: 13,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Plant'],
    globalRequirements: {Temperature: [-4, null]},
    production: {Plant: '3'},
    inventory: {Plant: '1'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText:
      'Requires -4\u00b0C or warmer. Increase your plant production 3 steps. Gain 1 plant.',
    effects: [ChangeProduction(3, ResourceType.Plant), ChangeInventory(1, ResourceType.Plant)],
    requires: [MinHeat(-4)],
  },
  {
    name: 'Great Escarpment Consortium',
    cost: 6,
    type: 'Automated',
    deck: 'Corporate',
    production: {Steel: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Requires that you have steel production. Decrease any steel production 1 step and increase your own 1 step',
    effects: [
      DecreaseAnyProduction(1, ResourceType.Steel),
      ChangeProduction(1, ResourceType.Steel),
    ],
  },
  {
    name: 'Mineral Deposit',
    cost: 5,
    type: 'Event',
    deck: 'Corporate',
    tags: ['Event'],
    inventory: {Steel: '5'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Gain 5 steel.',
    effects: [ChangeInventory(5, ResourceType.Steel)],
  },
  {
    name: 'Mining Expedition',
    cost: 12,
    type: 'Event',
    deck: 'Basic',
    tags: ['Event'],
    inventory: {Steel: '2', Plant: 'Ref'},
    terraforming: {Temperature: 0, Oxygen: 1, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Raise oxygen 1 step. Remove 2 plants from any player. Gain 2 steel.',
    effects: [
      RaiseOxygen(1),
      DecreaseAnyInventory(2, ResourceType.Plant),
      ChangeInventory(2, ResourceType.Steel),
    ],
  },
  {
    name: 'Mining Area',
    cost: 4,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Building'],
    production: {Steel: 'Ref', Titanium: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText:
      'Place [the mining] tile on an area with a steel or titanium placement bonus, adjacent to another of your tiles. Increase your production of that resource 1 step.',
  },
  {
    name: 'Building Industries',
    cost: 6,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Building'],
    production: {Steel: '2', Energy: '-1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Decrease your energy production 1 step and increase your steel production 2 steps.',
    effect: [ChangeProduction(1, ResourceType.Energy), ChangeProduction(2, ResourceType.Steel)],
  },
  {
    name: 'Land Claim',
    cost: 1,
    type: 'Event',
    deck: 'Corporate',
    tags: ['Event'],
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText: 'Place your marker on a non-reserved area. Only you may place a tile here',
    effect: [LandClaim],
  },
  {
    name: 'Mining Rights',
    cost: 9,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building'],
    production: {Steel: 'Ref', Titanium: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText:
      'Place [the mining] tile on an area with a steel or titanium placement bonus. Increase that production 1 step.',
  },
  {
    name: 'Sponsors',
    cost: 6,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Earth'],
    production: {Money: '2'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your MC production 2  steps.',
    effects: [ChangeProduction(2, ResourceType.Money)],
  },
  {
    name: 'Electro Catapult',
    cost: 17,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Building'],
    globalRequirements: {Oxygen: [null, 8]},
    production: {Energy: '-1'},
    inventory: {Money: 'Ref', Steel: 'Ref', Plant: 'Ref'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    actionText: 'Action: Spend 1 plant or 1 steel to gain 7 MC',
    effectText: 'Oxygen must be 8% or less. Decrease your energy production 1 step.',
    effects: [ChangeProduction(-1, ResourceType.Energy)],
    actions: [
      [
        Choice(ChangeInventory(1, ResourceType.Plant), ChangeInventory(1, ResourceType.Steel)),
        ChangeInventory(7, ResourceType.Money),
      ],
    ],
    requires: [MaxOxygen(8)],
  },
  {
    name: 'Earth Catapult',
    cost: 23,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Earth'],
    TR: 0,
    vp: 2,
    placeTiles: false,
    actionText: 'Effect: when you play a card, you pay 2 MC less for it.',
    triggers: [Discount(2)],
  },
  {
    name: 'Advanced Alloys',
    cost: 9,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Science'],
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText:
      'Effect: Each titanium you have is worth 1MC extra. Each steel you have is worth 1 MC extra.',
    // TODO
  },
  {
    name: 'Birds',
    cost: 10,
    type: 'Active',
    deck: 'Basic',
    tags: ['Animal'],
    globalRequirements: {Oxygen: [13, null]},
    production: {Plant: 'Ref'},
    TR: 0,
    placeTiles: false,
    actionText: 'Action: Add an animal to this card.',
    effectText:
      'Requires 13% oxygen. Decrease any plant production 2 steps. 1 VP for each animal on this card',
    actions: [[ChangeCardResource(1, CardResource.Animals)]],
    effects: [DecreaseAnyProduction(2, ResourceType.Plant)],
    resourceHeld: CardResource.Animals,
    requires: [MinOxygen(13)],
  },
  {
    name: 'Mars University',
    cost: 8,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Science', 'Building'],
    TR: 0,
    vp: 1,
    placeTiles: false,
    actionText:
      'Effect: When you play a science tag, including this, you may discard a card from hand to draw a card.',
  },
  {
    name: 'Viral Enhancers',
    cost: 9,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Science', 'Microbe'],
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText:
      'Effect: When you play a plant, microbe, or an animal tag, including this, gain 1 plant or add 1 resource TO THAT CARD.',
    // TODO,
  },
  {
    name: 'Towing a Comet',
    cost: 23,
    type: 'Event',
    deck: 'Basic',
    tags: ['Space', 'Event'],
    inventory: {Plant: '2'},
    terraforming: {Temperature: 0, Oxygen: 1, Ocean: 1},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText: 'Gain 2 plants. Raise oxygen level 1 step and place an ocean tile.',
    effects: [ChangeInventory(2, ResourceType.Plant), RaiseOxygen(1), PlaceOceans(1)],
  },
  {
    name: 'Space Mirrors',
    cost: 3,
    type: 'Active',
    deck: 'Basic',
    tags: ['Space', 'Energy'],
    production: {Energy: 'Ref'},
    inventory: {Money: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Action: Spend 7MC to increase your energy production 1 step.',
    actions: [[ChangeInventory(7, ResourceType.Money), ChangeProduction(1, ResourceType.Energy)]],
  },
  {
    name: 'Solar Wind Power',
    cost: 11,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Science', 'Space', 'Energy'],
    production: {Energy: '1'},
    inventory: {Titanium: '2'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your energy production 1 step and gain 2 titanium.',
    effects: [ChangeProduction(1, ResourceType.Energy), ChangeInventory(2, ResourceType.Titanium)],
  },
  {
    name: 'Ice Asteroid',
    cost: 23,
    type: 'Event',
    deck: 'Basic',
    tags: ['Space', 'Event'],
    terraforming: {Temperature: 0, Oxygen: 0, Ocean: 2},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText: 'Place 2 ocean tiles.',
    effects: [PlaceOceans(2)],
  },
  {
    name: 'Quantum Extractor',
    cost: 13,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Science', 'Energy'],
    requirements: {Science: '4'},
    production: {Energy: '4'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Effect: When you play a space card, you pay 2 MC less for it',
    triggers: [Discount(2, [Tag.Space])],
    requires: [HasTags(4, Tag.Science)],
  },
  {
    name: 'Giant Ice Asteroid',
    cost: 36,
    type: 'Event',
    deck: 'Basic',
    tags: ['Space', 'Event'],
    inventory: {Plant: 'Ref'},
    terraforming: {Temperature: 2, Oxygen: 0, Ocean: 2},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText:
      'Raise temperature 2 steps and place 2 ocean tiles. Remove up to 6 plants from any plyer.',
    effects: [IncreaseTemperature(2), PlaceOceans(2), DecreaseAnyProduction(6, ResourceType.Plant)],
  },
  {
    name: 'Ganymede Colony',
    cost: 20,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Space', 'City', 'Jovian'],
    TR: 0,
    placeTiles: true,
    effectText:
      'Place a city tile ON THE RESERVED AREA [for Ganymede Colony]. 1 VP per Jovian tag you have.',
    // TODO
  },
  {
    name: 'Callisto Penal Mines',
    cost: 24,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Space', 'Jovian'],
    production: {Money: '3'},
    TR: 0,
    vp: 2,
    placeTiles: false,
    effectText: 'Increase your MC production 3 steps.',
    effects: [ChangeProduction(3, ResourceType.Money)],
  },
  {
    name: 'Giant Space Mirror',
    cost: 17,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Space', 'Energy'],
    production: {Energy: '3'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your energy production 3 steps.',
    effects: [ChangeProduction(3, ResourceType.Energy)],
  },
  {
    name: 'Trans-Neptune Probe',
    cost: 6,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Science', 'Space'],
    TR: 0,
    vp: 0,
    placeTiles: false,
    // TODO wat
  },
  {
    name: 'Commercial District',
    cost: 16,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Building'],
    production: {Money: '4', Energy: '-1'},
    TR: 0,
    placeTiles: true,
    effectText:
      'Decrease your energy production 1 step and increase your MC production 4 steps. Place [the commercial district] tile. 1 VP PER ADJACENT CITY TILE.',
    // TODO wat
  },
  {
    name: 'Robotic Workforce',
    cost: 9,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Science'],
    production: {
      Money: 'Ref',
      Steel: 'Ref',
      Titanium: 'Ref',
      Plant: 'Ref',
      Energy: 'Ref',
      Heat: 'Ref',
    },
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Duplicate only the production box of one of your building cards.',
    effects: [RoboticWorkforce],
  },
  {
    name: 'Grass',
    cost: 11,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Plant'],
    globalRequirements: {Temperature: [-16, null]},
    production: {Plant: '1'},
    inventory: {Plant: '3'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Requires -16\u00b0C or warmer. Increase your plant production 1 step. Gain 3 plants.',
    effects: [ChangeProduction(1, ResourceType.Plant), ChangeInventory(3, ResourceType.Plant)],
    requires: [MinHeat(-16)],
  },
  {
    name: 'Heather',
    cost: 6,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Plant'],
    globalRequirements: {Temperature: [-14, null]},
    production: {Plant: '1'},
    inventory: {Plant: '1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Requires -14\u00b0C or warmer. Increase your plant production 1 step. Gain 1 plant.',
    effects: [ChangeProduction(1, ResourceType.Plant), ChangeInventory(1, ResourceType.Plant)],
    requires: [MinHeat(-14)],
  },
  {
    name: 'Peroxide Power',
    cost: 7,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Energy'],
    production: {Money: '-1', Energy: '2'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Decrease your MC production 1 step and increase your energy production 2 steps.',
    effects: [ChangeProduction(-1, ResourceType.Money), ChangeInventory(2, ResourceType.Energy)],
  },
  {
    name: 'Research',
    cost: 11,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Science', 'Science'],
    TR: 0,
    vp: 2,
    placeTiles: false,
    effectText: 'Counts as playing 2 science cards. Draw 2 cards.',
    effects: [Draw(2)],
  },
  {
    name: 'Gene Repair',
    cost: 12,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Science'],
    requirements: {Science: '3'},
    production: {Money: '2'},
    TR: 0,
    vp: 2,
    placeTiles: false,
    effectText: 'Requires 3 science tags. Increase your MC production 2 steps.',
    effects: [ChangeProduction(2, ResourceType.Money)],
    requires: [HasTags(3, Tag.Science)],
  },
  {
    name: 'Io Mining Industries',
    cost: 41,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Space', 'Jovian'],
    production: {Money: '2', Titanium: '2'},
    TR: 0,
    placeTiles: false,
    effectText:
      'Increase your titanium production 2 steps and your MC production 2 steps. 1 VP per Jovian tag you have.',
    effects: [ChangeProduction(2, ResourceType.Titanium), ChangeProduction(2, ResourceType.Money)],
  },
  {
    name: 'Bushes',
    cost: 10,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Plant'],
    globalRequirements: {Temperature: [-10, null]},
    production: {Plant: '2'},
    inventory: {Plant: '2'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Requires -10\u00b0C or warmer. Increase your plant production 2 steps. Gain 2 plants.',
    effects: [ChangeProduction(2, ResourceType.Plant), ChangeInventory(2, ResourceType.Plant)],
    requires: [MinHeat(-10)],
  },
  {
    name: 'Mass Converter',
    cost: 8,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Science', 'Energy'],
    requirements: {Science: '5'},
    production: {Energy: '6'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Effect: When you play a space card, you pay 2 MC less for it.',
    effectText: 'Requires 5 science tags. Increase your energy production 6 steps.',
    triggers: [Discount(2, [Tag.Space])],
    effects: [ChangeProduction(6, ResourceType.Energy)],
    requires: [HasTags(5, Tag.Science)],
  },
  {
    name: 'Physics Complex',
    cost: 12,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Science', 'Building'],
    inventory: {Energy: 'Ref'},
    TR: 0,
    placeTiles: false,
    actionText: 'Action: Spend 6 energy to add a science resource to this card.',
    effectText: '2 VP for each science resource on this card.',
    actions: [
      [ChangeInventory(-6, ResourceType.Energy), ChangeCardResource(1, CardResource.Science)],
    ],
    resourceHeld: CardResource.Science,
  },
  {
    name: 'Greenhouses',
    cost: 6,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Plant'],
    inventory: {Plant: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Gain 1 plant for each city tile in play.',
    effects: [ChangeInventory(GetCities(), ResourceType.Plant)],
  },
  {
    name: 'Nuclear Zone',
    cost: 10,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Earth'],
    terraforming: {Temperature: 2, Oxygen: 0, Ocean: 0},
    TR: 0,
    vp: -2,
    placeTiles: true,
    effectText: 'Place [the nuclear zone] tile and raise the temperature 2 steps.',
    // TODO
  },
  {
    name: 'Tropical Resort',
    cost: 13,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Building'],
    production: {Money: '3', Heat: '-2'},
    TR: 0,
    vp: 2,
    placeTiles: false,
    effectText: 'Decrease your heat production 2 steps and increase your MC production 3 steps.',
    effects: [ChangeProduction(-2, ResourceType.Heat), ChangeProduction(3, ResourceType.Money)],
  },
  {
    name: 'Toll Station',
    cost: 12,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Space'],
    production: {Money: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your MC production 1 step for each space tag your OPPONENTS have.',
    effects: [ChangeProduction(GetOpponentTags(Tag.Space), ResourceType.Money)],
  },
  {
    name: 'Fueled Generators',
    cost: 1,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Energy'],
    production: {Money: '-1', Energy: '1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Decrease your MC production 1 step and increase your energy production 1 step.',
    effects: [ChangeProduction(-1, ResourceType.Money), ChangeProduction(1, ResourceType.Energy)],
  },
  {
    name: 'Ironworks',
    cost: 11,
    type: 'Active',
    deck: 'Basic',
    tags: ['Building'],
    inventory: {Steel: 'Ref', Energy: 'Ref'},
    terraforming: {Temperature: 0, Oxygen: null, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Action: Spend 4 energy to gain 1 steel and increase oxygen 1 step.',
    actions: [
      [
        ChangeInventory(-4, ResourceType.Energy),
        ChangeInventory(1, ResourceType.Steel),
        RaiseOxygen(1),
      ],
    ],
  },
  {
    name: 'Power Grid',
    cost: 18,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Energy'],
    production: {Energy: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Increase your energy production 1 step for each power tag you have, including this.)',
    effects: [ChangeProduction(GetTags(Tag.Power), ResourceType.Energy)],
  },
  {
    name: 'Steelworks',
    cost: 15,
    type: 'Active',
    deck: 'Basic',
    tags: ['Building'],
    inventory: {Steel: 'Ref', Energy: 'Ref'},
    terraforming: {Temperature: 0, Oxygen: null, Ocean: 0},
    TR: 0,
    placeTiles: false,
    actionText: 'Action: Spend 4 energy to gain 2 steel and increase oxygen 1 step.',
    actions: [
      [
        ChangeInventory(-4, ResourceType.Energy),
        ChangeInventory(2, ResourceType.Steel),
        RaiseOxygen(1),
      ],
    ],
  },
  {
    name: 'Ore Processor',
    cost: 13,
    type: 'Active',
    deck: 'Basic',
    tags: ['Building'],
    inventory: {Titanium: 'Ref', Plant: 'Ref'},
    terraforming: {Temperature: 0, Oxygen: null, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Action: Spend 4 energy to gain 1 titanium and increase oxygen 1 step.',
    actions: [
      [
        ChangeInventory(-4, ResourceType.Energy),
        ChangeInventory(1, ResourceType.Steel),
        RaiseOxygen(1),
      ],
    ],
  },
  {
    name: 'Earth Office',
    cost: 1,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Earth'],
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Effect: When you play an Earth tag, you pay 3 MC less for it.',
    triggers: [Discount(3, [Tag.Earth])],
  },
  {
    name: 'Acquired Company',
    cost: 10,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Earth'],
    production: {Money: '3'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your MC production 3 steps.',
    effects: [ChangeProduction(3, ResourceType.Money)],
  },
  {
    name: 'Media Archives',
    cost: 8,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Earth'],
    inventory: {Money: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Gain 1 MC for each event EVER PLAYED by all players',
    effects: [ChangeInventory(GetAllTags(Tag.Event), ResourceType.Money)],
  },
  {
    name: 'Open City',
    cost: 23,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'City'],
    globalRequirements: {Oxygen: [12, null]},
    production: {Money: '4', Energy: '-1'},
    inventory: {Plant: '2'},
    TR: 0,
    vp: 1,
    placeTiles: true,
    effectText:
      'Requires 12% oxygen. Decrease your energy production 1 step and increase your MC production 4 steps. Gain 2 plants and place a city tile.',
    effects: [
      ChangeProduction(-1, ResourceType.Energy),
      ChangeProduction(4, ResourceType.Money),
      ChangeInventory(2, ResourceType.Plant),
      PlaceCity,
    ],
    requires: [MinOxygen(12)],
  },
  {
    name: 'Media Group',
    cost: 6,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Earth'],
    inventory: {Money: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Effect: After you play an event card, you gain 3MC',
    triggers: [AfterCard([Tag.Event], [ChangeInventory(3, ResourceType.Money)])],
  },
  {
    name: 'Business Network',
    cost: 4,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Earth'],
    production: {Money: '-1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Action: Look at the top card and either buy it or discard it',
    effectText: 'Decrease your MC production 1 step.',
    // TODO act
    effects: [ChangeProduction(-1, ResourceType.Money)],
  },
  {
    name: 'Business Contacts',
    cost: 7,
    type: 'Event',
    deck: 'Corporate',
    tags: ['Earth', 'Event'],
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Look at the top 4 cards from the deck. Take 2 of them into hand and discard the other 2',
    // TODO
  },
  {
    name: 'Bribed Committee',
    cost: 7,
    type: 'Event',
    deck: 'Corporate',
    tags: ['Earth', 'Event'],
    TR: 2,
    vp: -2,
    placeTiles: false,
    effectText: 'Raise your terraform rating 2 steps.',
    effects: [IncreaseTR(2)],
  },
  {
    name: 'Solar Power',
    cost: 11,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Energy'],
    production: {Energy: '1'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText: 'Increase your energy production 1 step.',
    effects: [ChangeProduction(1, ResourceType.Energy)],
  },
  {
    name: 'Breathing Filters',
    cost: 11,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Science'],
    globalRequirements: {Oxygen: [7, null]},
    TR: 0,
    vp: 2,
    placeTiles: false,
    effectText: 'Requires 7% oxygen.',
    requires: [MinOxygen(7)],
  },
  {
    name: 'Artificial Photosynthesis',
    cost: 12,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Science'],
    production: {Plant: 'Ref', Energy: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your plant production 1 step or your energy production 2 steps.',
    effects: [
      Choice(ChangeProduction(1, ResourceType.Plant), ChangeProduction(2, ResourceType.Energy)),
    ],
  },
  {
    name: 'Artificial Lake',
    cost: 15,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building'],
    globalRequirements: {Temperature: [-6, null]},
    terraforming: {Temperature: 0, Oxygen: 0, Ocean: 1},
    TR: 0,
    vp: 1,
    placeTiles: true,
    effectText:
      'Requires -6\u00b0C or warmer. Place 1 ocean tile ON AN AREA NOT RESERVED FOR OCEAN.',
    effects: [ArtificialLake],
    requires: [MinHeat(-6)],
  },
  {
    name: 'Geothermal Power',
    cost: 11,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Energy'],
    production: {Energy: '2'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your energy production 2 steps.',
    effects: [ChangeProduction(2, ResourceType.Energy)],
  },
  {
    name: 'Farming',
    cost: 16,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Microbe'],
    globalRequirements: {Temperature: [4, null]},
    production: {Money: '2', Plant: '2'},
    inventory: {Plant: '2'},
    TR: 0,
    vp: 2,
    placeTiles: false,
    effectText:
      'Requires +4\u00b0C or warmer. Increase your MC production 2 steps and your plant production 2 steps. Gain 2 plants.',
    effects: [
      ChangeProduction(2, ResourceType.Money),
      ChangeProduction(2, ResourceType.Plant),
      ChangeInventory(2, ResourceType.Plant),
    ],
    requires: [MinHeat(4)],
  },
  {
    name: 'Dust Seals',
    cost: 2,
    type: 'Automated',
    deck: 'Basic',
    globalRequirements: {Oceans: [null, 3]},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText: 'Requires 3 or less ocean tiles.',
    requires: [MaxOceans(3)],
  },
  {
    name: 'Urbanized Area',
    cost: 10,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'City'],
    production: {Money: '2', Energy: '-1'},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText:
      'Decrease your energy production 1 step and increase your MC production 2 steps. Place a city tile ADJACENT TO AT LEAST 2 OTHER CITY TILES.',
    effects: [
      ChangeProduction(-1, ResourceType.Energy),
      ChangeProduction(2, ResourceType.Money),
      UrbanizedArea,
    ],
  },
  {
    name: 'Sabotage',
    cost: 1,
    type: 'Event',
    deck: 'Corporate',
    tags: ['Event'],
    inventory: {Money: 'Ref', Steel: 'Ref', Titanium: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Remove up to 3 titanium from any player, or 4 steel, or 7 MC.',
    effects: [
      Choice(
        DecreaseAnyInventory(3, ResourceType.Titanium),
        DecreaseAnyInventory(4, ResourceType.Steel),
        DecreaseAnyInventory(7, ResourceType.Money)
      ),
    ],
  },
  {
    name: 'Moss',
    cost: 4,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Plant'],
    globalRequirements: {Oceans: [3, null]},
    production: {Plant: '1'},
    inventory: {Plant: '-1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Requires 3 ocean tiles and that you lose 1 plant. Increase your plant production 1 step.',
    effects: [ChangeInventory(-1, ResourceType.Plant), ChangeProduction(1, ResourceType.Plant)],
    requires: [MinOceans(3)],
  },
  {
    name: 'Industrial Center',
    cost: 4,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Building'],
    production: {Steel: 'Ref'},
    inventory: {Money: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: true,
    actionText: 'Action: Spend 7 MC to increase your steel production 1 step.',
    effectText: 'Place [the Industrial Center] tile ADJACENT TO A CITY TILE.',
    // todo
  },
  {
    name: 'Hired Raiders',
    cost: 1,
    type: 'Event',
    deck: 'Corporate',
    tags: ['Event'],
    inventory: {Money: 'Ref', Steel: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Steal up to 2 steel, or 3MC from any player.',
    // todo
  },
  {
    name: 'Hackers',
    cost: 3,
    type: 'Automated',
    deck: 'Corporate',
    production: {Money: 'Ref', Energy: '-1'},
    TR: 0,
    vp: -1,
    placeTiles: false,
    effectText:
      'Decrease your energy production 1 step and any MC production 2 steps. Increase your MC production 2 steps.',
    effects: [
      ChangeProduction(-1, ResourceType.Energy),
      DecreaseAnyProduction(2, ResourceType.Money),
      ChangeProduction(2, ResourceType.Money),
    ],
  },
  {
    name: 'GHG Factories',
    cost: 11,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building'],
    production: {Energy: '-1', Heat: '4'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Decrease your energy production 1 step and increase your heat production 4 steps.',
    effects: [ChangeProduction(-1, ResourceType.Energy), ChangeProduction(4, ResourceType.Heat)],
  },
  {
    name: 'Subterranean Reservoir',
    cost: 11,
    type: 'Event',
    deck: 'Basic',
    tags: ['Event'],
    terraforming: {Temperature: 0, Oxygen: 0, Ocean: 1},
    TR: 0,
    placeTiles: true,
    effectText: 'Place 1 ocean tile.',
    effects: [PlaceOceans(1)],
  },
  {
    name: 'Ecological Zone',
    cost: 12,
    type: 'Active',
    deck: 'Basic',
    tags: ['Plant', 'Animal'],
    TR: 0,
    placeTiles: true,
    actionText:
      'Effect: When you play an animal or a plant tag (including these 2), add an animal to this card.',
    effectText:
      'Requires that you have a greenery tile. Place [the Ecological Zone] tile ADJACENT TO ANY GREENERY TILE. 1 VP per 2 animals on this card.',
    resourceHeld: CardResource.Animals,
  },
  {
    name: 'Zeppelins',
    cost: 13,
    type: 'Automated',
    deck: 'Basic',
    globalRequirements: {Oxygen: [5, null]},
    production: {Money: 'Ref'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText:
      'Requires 5% oxygen. Increase your MC production 1 step for each city tile ON MARS.',
    effects: [ChangeProduction(GetCitiesOnMars(), ResourceType.Money)],
    requires: [MinOxygen(5)],
  },
  {
    name: 'Worms',
    cost: 8,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Microbe'],
    globalRequirements: {Oxygen: [4, null]},
    production: {Plant: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Requires 4% oxygen. Increase your plant production 1 step for every 2 microbe tags you have, including this.',
    effects: [ChangeProduction(GetTags(Tag.Microbe, 2), ResourceType.Plant)],
    requires: [MinOxygen(5)],
  },
  {
    name: 'Decomposers',
    cost: 5,
    type: 'Active',
    deck: 'Basic',
    tags: ['Microbe'],
    globalRequirements: {Oxygen: [3, null]},
    TR: 0,
    placeTiles: false,
    actionText:
      'Effect: When you play an animal, plant, or microbe tag, including this, add a microbe to this card.',
    effectText: 'Requires 3# oxygen. 1 VP per 3 microbes on this card.',
    // todo
    resourceHeld: CardResource.Microbes,
    requires: [MinOxygen(3)],
  },
  {
    name: 'Fusion Power',
    cost: 14,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Science', 'Building', 'Energy'],
    requirements: {Energy: '2'},
    production: {Energy: '3'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Requires 2 power tags. Increase your energy production 3 steps.',
    effects: [ChangeProduction(3, ResourceType.Energy)],
    requires: [HasTags(2, Tag.Power)],
  },
  {
    name: 'Symbiotic Fungus',
    cost: 4,
    type: 'Active',
    deck: 'Basic',
    tags: ['Microbe'],
    globalRequirements: {Temperature: [-14, null]},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Action: Add a microbe to ANOTHER card.',
    effectText: 'Requires -14\u00b0C or warmer.',
    actions: [[ChangeAnyCardResource(1, CardResource.Microbes)]],
    requires: [MinHeat(-14)],
  },
  {
    name: 'Extreme-Cold Fungus',
    cost: 13,
    type: 'Active',
    deck: 'Basic',
    tags: ['Microbe'],
    globalRequirements: {Temperature: [null, -10]},
    inventory: {Plant: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Action: Gain 1 plant or add 2 microbes to ANOTHER card.',
    actions: [
      [
        Choice(
          ChangeInventory(1, ResourceType.Plant),
          ChangeAnyCardResource(2, CardResource.Microbes)
        ),
      ],
    ],
    effectText: 'It must be -10\u00b0C or colder.',
    requires: [MaxHeat(-10)],
  },
  {
    name: 'Advanced Ecosystems',
    cost: 11,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Microbe', 'Plant', 'Animal'],
    requirements: {Microbe: '1', Plant: '1', Animal: '1'},
    TR: 0,
    vp: 3,
    placeTiles: false,
    effectText: 'Requires a plant tag, a microbe tag, and an animal tag.',
    requires: [HasTags(1, Tag.Microbe), HasTags(1, Tag.Plant), HasTags(1, Tag.Animal)],
  },
  {
    name: 'Great Dam',
    cost: 12,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Energy'],
    globalRequirements: {Oceans: [4, null]},
    production: {Energy: '2'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText: 'Requires 4 ocean tiles. Increase your energy production 2 steps.',
    effects: [ChangeProduction(2, ResourceType.Energy)],
    requires: [MinOceans(4)],
  },
  {
    name: 'Cartel',
    cost: 8,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Earth'],
    production: {Money: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your MC production 1 step for each Earth tag you have, including this.',
    effects: [ChangeProduction(GetTags(Tag.Earth), ResourceType.Money)],
  },
  {
    name: 'Strip Mine',
    cost: 25,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building'],
    production: {Steel: '2', Titanium: '1', Energy: '-1'},
    terraforming: {Temperature: 0, Oxygen: 2, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Decrease your energy production 2 steps. Increase your steel production 2 steps and your titanium production 1 step. Raise oxygen 2 steps.',
    effects: [
      ChangeProduction(-2, ResourceType.Energy),
      ChangeProduction(2, ResourceType.Steel),
      ChangeProduction(1, ResourceType.Titanium),
      RaiseOxygen(2),
    ],
  },
  {
    name: 'Wave Power',
    cost: 8,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Energy'],
    globalRequirements: {Oceans: [3, null]},
    production: {Energy: '1'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText: 'Requires 3 ocean tiles. Increase your energy production 1 step.',
    effects: [ChangeProduction(1, ResourceType.Energy)],
    requires: [MinOceans(3)],
  },
  {
    name: 'Lava Flows',
    cost: 18,
    type: 'Event',
    deck: 'Basic',
    tags: ['Event'],
    terraforming: {Temperature: 2, Oxygen: 0, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText:
      'Raise the temperature 2 steps and place this [the Lava Flow] tile ON EITHER THARSIS THOLUS, ASCRAEUS MONS, PAVONIS MONS OR ARSIA MONS.',
    // todo
  },
  {
    name: 'Power Plant',
    cost: 4,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Energy'],
    production: {Energy: '1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your energy production 1 step.',
    effects: [ChangeProduction(1, ResourceType.Energy)],
  },
  {
    name: 'Mohole Area',
    cost: 20,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building'],
    production: {Heat: '4'},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText:
      'Increase your heat production 4 steps. Place [the Mohole Area] tile ON AN AREA RESERVED FOR OCEAN.',
    effects: [ChangeProduction(4, ResourceType.Heat), Mohole],
  },
  {
    name: 'Large Convoy',
    cost: 36,
    type: 'Event',
    deck: 'Basic',
    tags: ['Space', 'Earth', 'Event'],
    inventory: {Plant: 'Ref'},
    terraforming: {Temperature: 0, Oxygen: 0, Ocean: 1},
    TR: 0,
    vp: 2,
    placeTiles: true,
    effectText:
      'Place an ocean tile and draw 2 cards. Gain 5 plants, or add 4 animals to ANOTHER card.',
    effects: [
      PlaceOceans(1),
      Draw(2),
      Choice(
        ChangeInventory(5, ResourceType.Plant),
        ChangeAnyCardResource(4, CardResource.Animals)
      ),
    ],
  },
  {
    name: 'Titanium Mine',
    cost: 7,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Building'],
    production: {Titanium: '1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your titanium production 1 step.',
    effects: [ChangeProduction(1, ResourceType.Titanium)],
  },
  {
    name: 'Tectonic Stress Power',
    cost: 18,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Energy'],
    requirements: {Science: '2'},
    production: {Energy: '3'},
    TR: 1,
    vp: 1,
    placeTiles: false,
    effectText: 'Requires 2 science tags. Increase your energy production 3 steps.',
    effects: [ChangeProduction(3, ResourceType.Energy)],
    requires: [HasTags(2, Tag.Science)],
  },
  {
    name: 'Nitrophilic Moss',
    cost: 8,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Plant'],
    globalRequirements: {Oceans: [3, null]},
    production: {Plant: '2'},
    inventory: {Plant: '-2'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Requires 3 ocean tiles and that you lose 2 plants. Increase your plant production 2 steps.',
    effects: [ChangeInventory(-2, ResourceType.Plant), ChangeProduction(2, ResourceType.Plant)],
    requries: [MinOceans(3)],
  },
  {
    name: 'Herbivores',
    cost: 12,
    type: 'Active',
    deck: 'Basic',
    tags: ['Animal'],
    globalRequirements: {Oxygen: [8, null]},
    production: {Plant: 'Ref'},
    TR: 0,
    placeTiles: false,
    actionText: 'Effect: When you place a greenery tile, add an animal to this card.',
    effectText:
      'Requires 8% oxygen. Add 1 animal to this card. Decrease any plant production 1 step. 1 VP per 2 animals on this card.',
    // todo
    resourceHeld: CardResource.Animals,
    requires: [MinOxygen(8)],
  },
  {
    name: 'Insects',
    cost: 9,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Microbe'],
    globalRequirements: {Oxygen: [6, null]},
    production: {Plant: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Requires 6% oxygen. Increase your plant production 1 step for each plant tag you have.',
    effects: [ChangeProduction(GetTags(Tag.Plant), ResourceType.Plant)],
    requires: [MinOxygen(6)],
  },
  {
    name: "CEO's Favourite Project",
    cost: 1,
    type: 'Event',
    deck: 'Corporate',
    tags: ['Event'],
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Add 1 resource to a card with at least 1 resource on it.',
    // todo
  },
  {
    name: 'Anti-Gravity Technology',
    cost: 14,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Science'],
    requirements: {Science: '7'},
    TR: 0,
    vp: 3,
    placeTiles: false,
    actionText: 'Effect: when you play a card, you pay 2 MC less for it.',
    effectText: 'Requires 7 science tags.',
    triggers: [Discount(2)],
    requires: [HasTags(7, Tag.Science)],
  },
  {
    name: 'Investment Loan',
    cost: 3,
    type: 'Event',
    deck: 'Corporate',
    tags: ['Earth', 'Event'],
    production: {Money: '-1'},
    inventory: {Money: '10'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Decrease your MC production 1 step. Gain 10 MC.',
    effects: [ChangeProduction(-1, ResourceType.Money), ChangeInventory(10, ResourceType.Money)],
  },
  {
    name: 'Insulation',
    cost: 2,
    type: 'Automated',
    deck: 'Basic',
    production: {Money: 'Ref', Heat: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Decrease your heat production any number of steps and increase your MC production the same number of steps.',
    effects: [
      ChangeProduction(Neg(GetX), ResourceType.Heat),
      ChangeProduction(GetX, ResourceType.Money),
    ],
  },
  {
    name: 'Adaptation Technology',
    cost: 12,
    type: 'Active',
    deck: 'Basic',
    tags: ['Science'],
    TR: 0,
    vp: 1,
    placeTiles: false,
    actionText: 'Effect: Your global requirements are +2 or -2 steps, your choice in each case.',
    // todo
  },
  {
    name: 'Caretaker Contract',
    cost: 3,
    type: 'Active',
    deck: 'Corporate',
    inventory: {Heat: 'Ref'},
    vp: 0,
    placeTiles: false,
    actionText: 'Action: Spend 8 heat to increase your terraforming rating 1 step.',
    effectText: 'Requires 0\u00b0C or warmer.',
    actions: [[ChangeInventory(-8, ResourceType.Heat), IncreaseTR(1)]],
  },
  {
    name: 'Designed Microorganisms',
    cost: 16,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Science', 'Microbe'],
    globalRequirements: {Temperature: [null, -14]},
    production: {Plant: '2'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'It must be -14\u00b0C or colder. Increase your plant production 2 steps.',
    effects: [ChangeProduction(2, ResourceType.Plant)],
    requires: [MaxHeat(-14)],
  },
  {
    name: 'Standard Technology',
    cost: 6,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Science'],
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText:
      'Effect: After you pay for a standard project, except selling patents, you gain 3 MC.',
    // TODO
  },
  {
    name: 'Nitrite Reducing Bacteria',
    cost: 11,
    type: 'Active',
    deck: 'Basic',
    tags: ['Microbe'],
    vp: 0,
    placeTiles: false,
    actionText:
      'Action: Add 1 microbe to this card, or remove 3 microbes to increase your TR 1 step.',
    effectText: 'Add 3 microbes to this card.',
    actions: [[Choice(ChangeCardResource(1, CardResource.Microbes))]],
    effects: [ChangeCardResource(3, CardResource.Microbes)],
    resourceHeld: CardResource.Microbes,
    // todo
  },
  {
    name: 'Industrial Microbes',
    cost: 12,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Microbe'],
    production: {Steel: '1', Energy: '1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your energy production and your steel production 1 step each.',
    effects: [ChangeProduction(1, ResourceType.Energy), ChangeProduction(1, ResourceType.Steel)],
  },
  {
    name: 'Lichen',
    cost: 7,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Plant'],
    globalRequirements: {Temperature: [-24, null]},
    production: {Plant: '1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Requires -24\u00b0C or warmer. Increase your plant production 1 step.',
    effects: [ChangeProduction(1, ResourceType.Plant)],
    requires: [MinHeat(-24)],
  },
  {
    name: 'Power Supply Consortium',
    cost: 5,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Energy'],
    requirements: {Energy: '2'},
    production: {Energy: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Requires 2 power tags. Decrease any energy production 1 step and increase your own 1 step.',
    effects: [
      DecreaseAnyProduction(1, ResourceType.Energy),
      ChangeProduction(1, ResourceType.Energy),
    ],
    requires: [HasTags(2, Tag.Power)],
  },
  {
    name: 'Convoy From Europa',
    cost: 15,
    type: 'Event',
    deck: 'Basic',
    tags: ['Space', 'Event'],
    terraforming: {Temperature: 0, Oxygen: 0, Ocean: 1},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText: 'Place 1 ocean tile and draw 1 card.',
    effects: [PlaceOceans(1), Draw(1)],
  },
  {
    name: 'Imported GHG',
    cost: 7,
    type: 'Event',
    deck: 'Basic',
    tags: ['Space', 'Earth', 'Event'],
    production: {Heat: '1'},
    inventory: {Heat: '3'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your heat production 1 step and gain 3 heat.',
    effects: [ChangeProduction(1, ResourceType.Heat), ChangeInventory(3, ResourceType.Heat)],
  },
  {
    name: 'Imported Nitrogen',
    cost: 23,
    type: 'Event',
    deck: 'Basic',
    tags: ['Space', 'Earth', 'Event'],
    TR: 1,
    vp: 0,
    effectText:
      'Raise your TR 1 step and gain 4 plants. Add 3 microbes to ANOTHER card and 2 animals to ANOTHER card.',
    effects: [
      IncreaseTR(1),
      ChangeInventory(4, ResourceType.Plant),
      ChangeAnyCardResource(3, CardResource.Microbes),
      ChangeAnyCardResource(2, CardResource.Animals),
    ],
  },
  {
    name: 'Micro-Mills',
    cost: 3,
    type: 'Automated',
    deck: 'Basic',
    production: {Heat: '1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your heat production 1 step.',
    effects: [ChangeProduction(1, ResourceType.Heat)],
  },
  {
    name: 'Magnetic Field Generators',
    cost: 20,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building'],
    production: {Plant: '2', Energy: '-4'},
    TR: 3,
    vp: 0,
    placeTiles: false,
    effectText:
      'Decrease your energy production 4 steps and increase your plant production 2 steps. Raise your TR 3 steps.',
    effects: [
      ChangeProduction(-4, ResourceType.Energy),
      ChangeProduction(2, ResourceType.Plant),
      IncreaseTR(3),
    ],
  },
  {
    name: 'Shuttles',
    cost: 10,
    type: 'Active',
    deck: 'Basic',
    tags: ['Space'],
    globalRequirements: {Oxygen: [6, null]},
    production: {Money: '2', Energy: '-1'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    actionText: 'Effect: When you play a space card, you pay 2MC less for it.',
    effectText:
      'Requires 5% oxygen. Decrease your energy production 1 step and increase your MC production 2 steps.',
    effects: [ChangeProduction(-1, ResourceType.Energy), ChangeProduction(2, ResourceType.Money)],
    requires: [MinOxygen(6)],
  },
  {
    name: 'Import of Advanced GHG',
    cost: 9,
    type: 'Event',
    deck: 'Basic',
    tags: ['Space', 'Earth', 'Event'],
    production: {Heat: '2'},
    TR: 0,
    placeTiles: false,
    effectText: 'Increase your heat production 2 steps.',
    effects: [ChangeProduction(2, ResourceType.Heat)],
  },
  {
    name: 'Windmills',
    cost: 6,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Energy'],
    globalRequirements: {Oxygen: [7, null]},
    production: {Energy: '1'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText: 'Requires 7% oxygen. Increase your energy production 1 step.',
    effectd: [ChangeProduction(1, ResourceType.Energy)],
    requires: [MinOxygen(7)],
  },
  {
    name: 'Tundra Farming',
    cost: 16,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Plant'],
    globalRequirements: {Temperature: [-6, null]},
    production: {Money: '2', Plant: '1'},
    inventory: {Plant: '1'},
    TR: 0,
    vp: 2,
    placeTiles: false,
    effectText:
      'Requires -6\u00b0C or warmer. Increase your plant production 1 step and your MC production 2 steps. Gain 1 plant.',
    effects: [
      ChangeProduction(1, ResourceType.Plant),
      ChangeProduction(2, ResourceType.Money),
      ChangeInventory(1, ResourceType.Plant),
    ],
    requires: [MinHeat(-6)],
  },
  {
    name: 'Aerobraked Ammonia Asteroid',
    cost: 26,
    type: 'Event',
    deck: 'Basic',
    tags: ['Space', 'Event'],
    production: {Plant: '1', Heat: '3'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Add 2 microbes to ANOTHER card. Increase your heat production 3 steps and your plant production 1 step.',
    effects: [
      ChangeAnyCardResource(2, CardResource.Microbes),
      ChangeProduction(3, ResourceType.Heat),
      ChangeProduction(1, ResourceType.Plant),
    ],
  },
  {
    name: 'Magnetic Field Dome',
    cost: 5,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building'],
    production: {Plant: '1', Energy: '-2'},
    TR: 1,
    vp: 0,
    placeTiles: false,
    effectText:
      'Decrease your energy production 2 steps and increase your plant production 1 step. Raise your terraform rating 1 step.',
    effects: [
      ChangeProduction(-2, ResourceType.Energy),
      ChangeProduction(1, ResourceType.Plant),
      IncreaseTR(1),
    ],
  },
  {
    name: 'Pets',
    cost: 10,
    type: 'Active',
    deck: 'Basic',
    tags: ['Animal', 'Earth'],
    TR: 0,
    placeTiles: false,
    actionText:
      'Effect: When any city tile is placed, add an animal to this card. Animals may not be removed from this card.',
    effectText: 'Add 1 animal to this card. 1 VP per 2 animals here.',
    resourceHeld: CardResource.Animals,
    // todo
  },
  {
    name: 'Protected Habitats',
    cost: 5,
    type: 'Active',
    deck: 'Corporate',
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: '[Effect: ]Opponents may not remove your [plants, animals or microbes]',
    // todo
  },
  {
    name: 'Protected Valley',
    cost: 23,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Plant'],
    production: {Money: '2'},
    terraforming: {Temperature: 0, Oxygen: 1, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText:
      'Increase your MC production 2 steps. Place a greenery tile ON AN AREA RESERVED FOR OCEAN, disregarding normal placement restrictions, and increase oxygen 1 step.',
    effects: [ChangeProduction(2, ResourceType.Money), PlaceGreeneryOnOcean],
  },
  {
    name: 'Satellites',
    cost: 10,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Space'],
    production: {Money: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Increase your MC production 1 step for each space tag you have, including this one.',
    effects: [ChangeProduction(GetTags(Tag.Space), ResourceType.Money)],
  },
  {
    name: 'Noctis Farming',
    cost: 10,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Plant'],
    globalRequirements: {Temperature: [-20, null]},
    production: {Money: '1'},
    inventory: {Plant: '2'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText:
      'Requires -20\u00b0C or warmer. Increase your MC production 1 step and gain 2 plants.',
    effects: [ChangeProduction(1, ResourceType.Money), ChangeInventory(2, ResourceType.Plant)],
    requires: [MinHeat(-20)],
  },
  {
    name: 'Water Splitting Plant',
    cost: 12,
    type: 'Active',
    deck: 'Basic',
    tags: ['Building'],
    globalRequirements: {Oceans: [2, null]},
    inventory: {Energy: 'Ref'},
    terraforming: {Temperature: 0, Oxygen: null, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Action: Spend 3 energy to raise oxygen 1 step.',
    effectText: 'Requires 2 ocean tiles.',
    actions: [[ChangeInventory(-3, ResourceType.Energy), RaiseOxygen(1)]],
    requires: [MinOceans(2)],
  },
  {
    name: 'Heat Trappers',
    cost: 6,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Energy'],
    production: {Energy: '1'},
    inventory: {Heat: 'Ref'},
    TR: 0,
    vp: -1,
    placeTiles: false,
    effectText: 'Decrease any heat production 2 steps and increase your energy production 1 step.',
    effects: [
      DecreaseAnyProduction(2, ResourceType.Heat),
      ChangeProduction(1, ResourceType.Energy),
    ],
  },
  {
    name: 'Soil Factory',
    cost: 9,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building'],
    production: {Plant: '1', Energy: '-1'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText: 'Decrease your energy production 1 step and increase your plant production 1 step.',
    effects: [ChangeProduction(-1, ResourceType.Energy), ChangeProduction(1, ResourceType.Plant)],
  },
  {
    name: 'Fuel Factory',
    cost: 6,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Building'],
    production: {Money: '1', Titanium: '1', Energy: '-1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Decreases your energy production 1 step and increase your titanium and your MC production 1 step each.',
    effects: [
      ChangeProduction(-1, ResourceType.Energy),
      ChangeProduction(1, ResourceType.Titanium),
      ChangeProduction(1, ResourceType.Money),
    ],
  },
  {
    name: 'Ice cap Melting',
    cost: 5,
    type: 'Event',
    deck: 'Basic',
    tags: ['Event'],
    globalRequirements: {Temperature: [2, null]},
    terraforming: {Temperature: 0, Oxygen: 0, Ocean: 1},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText: 'Requires +2\u00b0C or warmer. Place 1 ocean tile.',
    effects: [PlaceOceans(1)],
    requires: [MinHeat(2)],
  },
  {
    name: 'Corporate Stronghold',
    cost: 11,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Building', 'City'],
    production: {Money: '3', Energy: '-1'},
    TR: 0,
    vp: -2,
    placeTiles: true,
    effectText:
      'Decrease your energy production 1 step and increase your MC production 3 steps. Place a city tile.',
    effects: [
      ChangeProduction(-1, ResourceType.Energy),
      ChangeProduction(3, ResourceType.Money),
      PlaceCity,
    ],
  },
  {
    name: 'Biomass Combustors',
    cost: 4,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building', 'Energy'],
    globalRequirements: {Oxygen: [6, null]},
    production: {Plant: 'Ref', Energy: '2'},
    TR: 0,
    vp: -1,
    placeTiles: false,
    effectText:
      'Requires 6% oxygen. Decrease any plant production 1 step and increase your energy production 2 steps.',
    effects: [
      DecreaseAnyProduction(1, ResourceType.Plant),
      ChangeProduction(2, ResourceType.Energy),
    ],
    requires: [MinOxygen(6)],
  },
  {
    name: 'Livestock',
    cost: 13,
    type: 'Active',
    deck: 'Basic',
    tags: ['Animal'],
    globalRequirements: {Oxygen: [9, null]},
    production: {Money: '2', Plant: '-1'},
    TR: 0,
    placeTiles: false,
    actionText: 'Action: Add 1 animal to this card.',
    effectText:
      'Requires 9% oxygen. Decrease your plant production 1 step and increase your MC production 2 steps. 1 VP for each animal on this card.',
    actions: [[ChangeCardResource(1, CardResource.Animals)]],
    effects: [ChangeProduction(-1, ResourceType.Plant), ChangeProduction(2, ResourceType.Money)],
    resourceHeld: CardResource.Animals,
    requires: [MinOxygen(9)],
  },
  {
    name: 'Olympus Conference',
    cost: 10,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Science', 'Building', 'Earth'],
    TR: 0,
    vp: 1,
    placeTiles: false,
    actionText:
      'Effect: When you play a science tag, including this, either add a science resource to this card, or remove a science resource from this card to draw a card.',
    resourceHeld: CardResource.Science,
    // todo
  },
  {
    name: 'Rad-Suits',
    cost: 6,
    type: 'Automated',
    deck: 'Corporate',
    requirements: {City: 'Ref'},
    production: {Money: '1'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText: 'Requires 2 cities in play. Increase your MC production 1 step.',
    effects: [ChangeProduction(1, ResourceType.Money)],
    requires: [HasCitiesOnMars(1)],
  },
  {
    name: 'Aquifer Pumping',
    cost: 18,
    type: 'Active',
    deck: 'Basic',
    tags: ['Building'],
    inventory: {Money: 'Ref', Steel: 'Ref'},
    terraforming: {Temperature: 0, Oxygen: 0, Ocean: null},
    TR: 0,
    vp: 0,
    placeTiles: true,
    actionText:
      'Action: Spend 8 MC to place 1 ocean tile. STEEL MAY BE USED as if you were playing a building card.',
    // todo
  },
  {
    name: 'Flooding',
    cost: 7,
    type: 'Event',
    deck: 'Basic',
    tags: ['Event'],
    inventory: {Money: 'Ref'},
    terraforming: {Temperature: 0, Oxygen: 0, Ocean: 1},
    TR: 0,
    vp: -1,
    placeTiles: true,
    effectText:
      'Place an ocean tile. IF THERE ARE TILES ADJACENT TO THIS OCEAN TILE, YOU MAY REMOVE 4 MC FROM THE OWNER OF ONE OF THOSE TILES.',
    // todo
  },
  {
    name: 'Energy Saving',
    cost: 15,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Energy'],
    production: {Energy: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your energy production 1 step for each city tile in play.',
    effects: [ChangeProduction(GetCities(), ResourceType.Energy)],
  },
  {
    name: 'Local Heat Trapping',
    cost: 1,
    type: 'Event',
    deck: 'Basic',
    tags: ['Event'],
    inventory: {Plant: 'Ref', Heat: '-5'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Spend 5 heat to either gain 4 plants, or to add 2 animals to ANOTHER card.',
    // todo
  },
  {
    name: 'Permafrost extraction',
    cost: 8,
    type: 'Event',
    deck: 'Basic',
    tags: ['Event'],
    globalRequirements: {Temperature: [-8, null]},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText: 'Requires -8\u00b0C or warmer. Place 1 ocean tile.',
    effects: [PlaceOceans(1)],
    requires: [MinHeat(-8)],
  },
  {
    name: 'Invention Contest',
    cost: 2,
    type: 'Event',
    deck: 'Corporate',
    tags: ['Science', 'Event'],
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Look at the top 3 cards from the deck. Take 1 of them into hand and discard the other 2',
    //todo
  },
  {
    name: 'Plantation',
    cost: 15,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Plant'],
    requirements: {Science: '2'},
    terraforming: {Temperature: 0, Oxygen: 1, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: true,
    effectText: 'Requires 2 science tags. Place a greenery tile and raise oxygen 1 step.',
    effects: [PlaceGreenery],
    requires: [HasTags(2, Tag.Science)],
  },
  {
    name: 'Power Infrastructure',
    cost: 4,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Building', 'Energy'],
    inventory: {Money: 'Ref', Energy: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Action: Spend any amount of energy to gain that amount of MC.',
    actions: [
      [ChangeInventory(Neg(GetX), ResourceType.Energy), ChangeInventory(GetX, ResourceType.Money)],
    ],
  },
  {
    name: 'Indentured Workers',
    cost: 0,
    type: 'Event',
    deck: 'Corporate',
    tags: ['Event'],
    TR: 0,
    vp: -1,
    placeTiles: false,
    effectText: 'The next card you play this generation costs 8MC less.',
    // todo
  },
  {
    name: 'Lagrange Observatory',
    cost: 9,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Science', 'Space'],
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText: 'Draw 1 card.',
    effects: [Draw(1)],
  },
  {
    name: 'Terraforming Ganymede',
    cost: 33,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Space', 'Jovian'],
    vp: 2,
    placeTiles: false,
    effectText: 'Raise your TR 1 step for each Jovian tag you have, including this.',
    effects: [IncreaseTR(GetTags(Tag.Jovian))],
  },
  {
    name: 'Immigration Shuttles',
    cost: 31,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Space', 'Earth'],
    production: {Money: '5'},
    TR: 0,
    placeTiles: false,
    effectText: 'Increase your MC production 5 steps. 1 VP for every 3rd city in play.',
    effects: [ChangeProduction(5, ResourceType.Money)],
  },
  {
    name: 'Restricted Area',
    cost: 11,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Science'],
    inventory: {Money: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: true,
    actionText: 'Action: Spend 2MC to draw a card.',
    effectText: 'Place [the restricted area] tile.',
    // todo
  },
  {
    name: 'Immigrant City',
    cost: 13,
    type: 'Active',
    deck: 'Basic',
    tags: ['Building', 'City'],
    production: {Money: 'Ref', Energy: '-1'},
    TR: 0,
    vp: 0,
    placeTiles: true,
    actionText:
      'Effect: Each time a city tile is placed, including this, increase your MC production 1 step.',
    effectText:
      'Decrease your energy production 1 step and decrease your MC production 2 steps. Place a city tile.',
    //todo
  },
  {
    name: 'Energy Tapping',
    cost: 3,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Energy'],
    production: {Energy: 'Ref'},
    TR: 0,
    vp: -1,
    placeTiles: false,
    effectText: 'Decrease any energy production 1 step and increase your own 1 step.',
    effects: [
      DecreaseAnyProduction(1, ResourceType.Energy),
      ChangeProduction(1, ResourceType.Energy),
    ],
  },
  {
    name: 'Underground Detonations',
    cost: 6,
    type: 'Active',
    deck: 'Basic',
    tags: ['Building'],
    production: {Heat: 'Ref'},
    inventory: {Money: 'Ref'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText: 'Action: Spend 10 MC to increase your heat production 2 steps.',
    actions: [[ChangeInventory(-10, ResourceType.Money), ChangeProduction(2, ResourceType.Heat)]],
  },
  {
    name: 'Soletta',
    cost: 35,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Space'],
    production: {Heat: '7'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase your heat production 7 steps.',
    effects: [ChangeProduction(7, ResourceType.Heat)],
  },
  {
    name: 'Technology Demonstration',
    cost: 5,
    type: 'Event',
    deck: 'Corporate',
    tags: ['Science', 'Space', 'Event'],
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Draw 2 cards.',
    effects: [Draw(2)],
  },
  {
    name: 'Rad-Chem Factory',
    cost: 8,
    type: 'Automated',
    deck: 'Basic',
    tags: ['Building'],
    production: {Energy: '-1'},
    TR: 2,
    vp: 0,
    placeTiles: false,
    effectText: 'Decrease your energy production 1 step. Raise your terraform rating 2 steps.',
    effects: [ChangeProduction(-1, ResourceType.Energy), IncreaseTR(2)],
  },
  {
    name: 'Special Design',
    cost: 4,
    type: 'Event',
    deck: 'Basic',
    tags: ['Science', 'Event'],
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'The next card you play this generation is +2 or -2 in global requirements, your choice.',
    // todo
  },
  {
    name: 'Medical Lab',
    cost: 13,
    type: 'Automated',
    deck: 'Corporate',
    tags: ['Science', 'Building'],
    production: {Money: 'Ref'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    effectText:
      'Increase your MC production 1 step for every 2 building tags you have, including this.',
    effects: [ChangeProduction(GetTags(Tag.Building, 2), ResourceType.Money)],
  },
  {
    name: 'AI Central',
    cost: 21,
    type: 'Active',
    deck: 'Corporate',
    tags: ['Science', 'Building'],
    requirements: {Science: '3'},
    production: {Energy: '-1'},
    TR: 0,
    vp: 1,
    placeTiles: false,
    actionText: 'Action: Draw 2 cards.',
    effectText: 'Requires 3 science tags to play. Decrease your energy production 1 step.',
    actions: [[Draw(2)]],
    effects: [ChangeProduction(-1, ResourceType.Energy)],
    requires: [HasTags(3, Tag.Science)],
  },
  {
    name: 'Small Asteroid',
    cost: 10,
    type: 'Event',
    deck: 'Promo',
    tags: ['Space', 'Event'],
    inventory: {Plant: 'Ref'},
    terraforming: {Temperature: 1, Oxygen: 0, Ocean: 0},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText: 'Increase temperature 1 step. Remove up to 2 plants from any player.',
    effects: [IncreaseTemperature(1), DecreaseAnyInventory(2, ResourceType.Plant)],
  },
  {
    name: 'Self-Replicating Robots',
    cost: 7,
    type: 'Active',
    deck: 'Promo',
    requirements: {Science: '2'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    actionText:
      'Action: Reveal and place a SPACE OR BUILDING card here from hand, and place 2 resources on it, OR double the resources on a card here. Effect: Cards here may be played as if from hand with its cost reduced by the number of resources on it.',
    effectText: 'Requires 2 science tags.',
    // todo,
    requires: [HasTags(2, Tag.Science)],
  },
  {
    name: 'Snow Algae',
    cost: 12,
    type: 'Active',
    deck: 'Promo',
    tags: ['Plant'],
    globalRequirements: {Oceans: [2, null]},
    production: {Plant: '1', Heat: '1'},
    TR: 0,
    vp: 0,
    placeTiles: false,
    effectText:
      'Requires 2 oceans. Increase your plant production and your heat production 1 step each.',
    requires: [MinOceans(2)],
    // todo
  },
]
