import {ResourceBonus, Position} from './types'

export const OCEAN_POSITIONS: Position[] = [
  [-3, 4],
  [-1, 4],
  [0, 4],
  [1, 3],
  [3, 1],
  [-1, 0],
  [0, 0],
  [1, 0],
  [2, -1],
  [3, -1],
  [4, -1],
  [4, -4],
]

export const VOLCANO_POSITIONS: Position[] = [[-4, 0], [-4, 1], [-4, 2], [-3, 3]]

export const RESOURCE_BONUSES = {
  '-4,4': [ResourceBonus.Steel, ResourceBonus.Steel],
  '-4,2': [ResourceBonus.Card],
  '-4,1': [ResourceBonus.Plant, ResourceBonus.Titanium],
  '-4,0': [ResourceBonus.Plant, ResourceBonus.Plant],
  '-3,4': [ResourceBonus.Steel, ResourceBonus.Steel],
  '-3,3': [ResourceBonus.Steel],
  '-3,1': [ResourceBonus.Plant],
  '-3,0': [ResourceBonus.Plant, ResourceBonus.Plant],
  '-3,-1': [ResourceBonus.Plant],
  '-2,1': [ResourceBonus.Plant],
  '-2,0': [ResourceBonus.Plant, ResourceBonus.Plant],
  '-2,-1': [ResourceBonus.Plant, ResourceBonus.Plant],
  '-1,4': [ResourceBonus.Card],
  '-1,1': [ResourceBonus.Plant],
  '-1,0': [ResourceBonus.Plant, ResourceBonus.Plant],
  '-1,-1': [ResourceBonus.Plant],
  '-1,-3': [ResourceBonus.Steel, ResourceBonus.Steel],
  '0,1': [ResourceBonus.Plant, ResourceBonus.Plant],
  '0,0': [ResourceBonus.Plant, ResourceBonus.Plant],
  '0,-1': [ResourceBonus.Plant],
  '0,-4': [ResourceBonus.Steel],
  '1,3': [ResourceBonus.Card, ResourceBonus.Card],
  '1,1': [ResourceBonus.Plant],
  '1,0': [ResourceBonus.Plant, ResourceBonus.Plant],
  '1,-1': [ResourceBonus.Plant],
  '1,-4': [ResourceBonus.Steel, ResourceBonus.Steel],
  '2,2': [ResourceBonus.Steel],
  '2,1': [ResourceBonus.Plant],
  '2,0': [ResourceBonus.Plant, ResourceBonus.Plant],
  '2,-1': [ResourceBonus.Plant],
  '2,-3': [ResourceBonus.Card],
  '3,1': [ResourceBonus.Plant, ResourceBonus.Plant],
  '3,0': [ResourceBonus.Plant, ResourceBonus.Plant],
  '3,-1': [ResourceBonus.Plant],
  '3,-2': [ResourceBonus.Plant],
  '4,0': [ResourceBonus.Plant, ResourceBonus.Plant],
  '4,-1': [ResourceBonus.Plant],
  '4,-3': [ResourceBonus.Titanium],
  '4,-4': [ResourceBonus.Titanium, ResourceBonus.Titanium],
}
